name: macOS build stub

on:
  workflow_dispatch:

jobs:
  buildMacOS:
    runs-on: ubuntu-latest
    steps:
      - name: Job info
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event }}"

      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Creating a stub
        run: echo "Hello world" > macos/PICSimLab.dmg

      - name: Upload artifacts macos-26
        uses: actions/upload-artifact@v7
        with:
          name: macos-26
          path: macos/PICSimLab.dmg

      - name: Upload artifacts macos-26
        uses: actions/upload-artifact@v7
        with:
          name: macos-26-intel
          path: macos/PICSimLab.dmg
